spring:
  application:
    name: agenticrag

  datasource:
    url: jdbc:mysql://10.60.31.253:3306/agenticrag?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 10.60.31.253
      port: 6379

  kafka:
    bootstrap-servers: 10.60.31.253:9092
    consumer:
      group-id: agenticrag-group

  elasticsearch:
    uris: http://10.60.31.253:9200

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

minio:
  endpoint: http://10.60.31.253:19000
  access-key: admin
  secret-key: PaiSmart2025
  bucket-name: agenticrag

rag:
  retrieval:
    knn-top-k: 20
    bm25-top-k: 20
    rerank-top-n: 5

langchain4j:
  llm:
    open-ai:
      base-url: "https://api.openai.com/v1"
      api-key: "sk-your-llm-api-key"
      model-name: "gpt-4o"
      temperature: 0.7
  embedding:
    open-ai:
      base-url: "https://api.openai.com/v1"
      api-key: "sk-your-embedding-api-key"
      model-name: "text-embedding-3-small"
  reranker:
    api-url: "https://api.jina.ai/v1/rerank"
    api-key: "jina_your_reranker_api_key"
    model-name: "jina-reranker-v2-base-multilingual"


jwt:
  secret: "4Z9Q8v/T2p+R1xE6wY7uI0oA4dL5sM3bF8G2hJ7vK1c="
  expiration: 86400000
server:
  port: 8000
